export const NOTE = {
  ADD_FORWARD: "NOTE/ADD_FORWARD",
  ADD_BACKWARD: "NOTE/ADD_BACKWARD",
  REMOVE_FIRST: "NOTE/REMOVE_FIRST",
  REMOVE_LAST: "NOTE/REMOVE_LAST",
  REMOVE_ALL: "NOTE/REMOVE_ALL",
} as const;
